platform:ios,'6.0'
target "ximituProject" do
pod 'YapDatabase'
pod 'JZNavigationExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'FPPopover'
pod 'MJRefresh'
pod 'Reachability'
pod 'DCKeyValueObjectMapping'
pod 'IQKeyboardManager'
pod 'JSONKit'
pod 'RegexKitLite'
pod 'SDWebImage'
pod 'VPImageCropper'
pod 'ZYQAssetPickerController'
pod 'SVProgressHUD', '~> 2.1'
pod 'JSONModel', '~> 1.7.0'
platform:ios,'7.0'
pod 'SDCycleScrollView'

end
